spring:
  datasource:
    url: jdbc:mysql://localhost:3306/teams_tracking
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

server:
  port: 8080

gps-api:
  base-url: https://desafio-media.onrender.com
  api-key: m4a_9d7f2c1ab84e6f03b2c91d5aa77e4c6f8b1d2e3f4a5b6c7